-- AlterTable
ALTER TABLE "Trade" ADD COLUMN     "commission" DOUBLE PRECISION,
ADD COLUMN     "lotSize" DOUBLE PRECISION,
ADD COLUMN     "stopLoss" DOUBLE PRECISION,
ADD COLUMN     "swap" DOUBLE PRECISION,
ADD COLUMN     "takeProfit" DOUBLE PRECISION;
