
import { Trade, TradeResult } from './types';

export const MOCK_TRADES: Trade[] = [
  {
    id: 1,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'GER40',
    direction: 'Sell',
    risk: '1%',
    strategy: 'S/D',
    execution: 'Manual Execution',
    entryPrice: 23588.06,
    exitPrice: 23638.97,
    profitLoss: 21.68,
    result: TradeResult.Loss,
    notes: 'Test entry, stopped quickly',
  },
  {
    id: 2,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'GER40',
    direction: 'Buy',
    risk: '1%',
    strategy: 'S/R',
    execution: 'Manual Execution',
    entryPrice: 23637.85,
    exitPrice: 23681.56,
    profitLoss: 13.44,
    result: TradeResult.Win,
    notes: 'Partial close',
  },
  {
    id: 3,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'GER40',
    direction: 'Buy',
    risk: '1%',
    strategy: 'T/L',
    execution: 'Manual Execution',
    entryPrice: 23637.85,
    exitPrice: 23681.56,
    profitLoss: 54.06,
    result: TradeResult.Win,
    notes: 'Clean trade, followed levels',
  },
  {
    id: 4,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'GER40',
    direction: 'Sell',
    risk: '1%',
    strategy: 'S/R',
    execution: 'Manual Execution',
    entryPrice: 23662.06,
    exitPrice: 23642.25,
    profitLoss: 23.44,
    result: TradeResult.Win,
    notes: 'Good read on momentum',
  },
  {
    id: 5,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'US100',
    direction: 'Sell',
    risk: '1%',
    strategy: 'S/D',
    execution: 'Manual Execution',
    entryPrice: 24478.95,
    exitPrice: 24507.21,
    profitLoss: 2.83,
    result: TradeResult.Loss,
    notes: 'Small test size',
  },
  {
    id: 6,
    date: '18/09/25',
    day: 'Thursday',
    asset: 'US100',
    direction: 'Sell',
    risk: '1%',
    strategy: 'S/D',
    execution: 'Manual Execution',
    entryPrice: 24482.95,
    exitPrice: 24505.05,
    profitLoss: 22.1,
    result: TradeResult.Loss,
    notes: 'Cut quickly, timing off',
  },
];
