# AUTO-GENERATED by DockCtrl
# Framework: Node.js
# Build: Multi-stage for optimal image size
# Security: Non-root user, minimal attack surface

FROM node:22-alpine AS deps
WORKDIR /app

# Install dependencies based on package manager

COPY package.json package-lock.json* ./
RUN npm ci --only=production


FROM node:22-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

# Use existing node user from base image (DO NOT create new one)
RUN chown -R node:node /app

COPY --from=deps --chown=node:node /app/node_modules ./node_modules
COPY --chown=node:node . .

USER node

EXPOSE 3000
ENV PORT=3000

# Install wget for health checks
USER root
RUN apk add --no-cache wget
USER node

HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
  CMD wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1

CMD ["npm", "start"]
